name: Continuous Integration
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: leojgpereira/csr-core-service-api/.github/actions/setup@main
      - uses: leojgpereira/csr-core-service-api/.github/actions/build@main